### ISSUE TITLE
This is just wrong

### ISSUE THREAD

**Issue by ForceTower** [GustavoHBO/Compiler_EXA869#1]
Your default IDE is Netbeans....
Don't do this to yourself, use something better.

**Comment by GustavoHBO** [comment]
Hue, 
I will download the Android Studio, to program with Kotlin and run on PC with help of emulators. Thank you, was a moment of crazy mine.

**Comment by ForceTower** [comment]
Good to know.
I hope to see you using Intellij Products from now on :)

**Comment by GustavoHBO** [comment]
I will try, but not promise.
